Add pre-commit hooks to poprox-concepts
CCRI-POPROX/poprox-concepts pull request #13
Opened 2024-07-16 16:10 UTC by kluver

One thing I want a second opinion on: 

I changed the name of `Tracking_Link_Data` to `TrackingLinkData` I tried to make it backwards compatible until we can update imports elsewhere, but I'm not confident that this is the right way to do it.

2024-07-16 18:27 UTC, mdekstrand requested changes
there's a `pyproject copy.toml` instead of `pyproject.toml`?

name is fine with me.

2024-07-16 18:32 UTC, kluver commented
> there's a `pyproject copy.toml` instead of `pyproject.toml`?
Good catch. I knew something goofy was happening, but I couldn't place it.

2024-07-16 21:05 UTC, karlhigley commented
Re: backwards compatibility, this should work and we don't have to worry a ton about making it perfect because instead we should make it go away. I'm planning to do exactly the same thing when I rename repository class methods Soon™

2024-07-18 21:33 UTC, karlhigley approved these changes

2024-07-18 21:33 UTC, merged